CSPC/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('CSPCApp.urls')),
]

CSPCApp/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'student', api.StudentViewSet)
router.register(r'course', api.CourseViewSet)
router.register(r'courseobject', api.CourseObjectViewSet)
router.register(r'userinfo', api.UserInfoViewSet)
router.register(r'contract', api.ContractViewSet)
router.register(r'contractendinfo', api.ContractEndInfoViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Student

    url(r'^CSPCApp/student/$', views.StudentListView.as_view(), name='CSPCApp_student_list'),
    url(r'^CSPCApp/student/create/$', views.StudentCreateView.as_view(), name='CSPCApp_student_create'),
    url(r'^CSPCApp/student/detail/(?P<pk>\S+)/$', views.StudentDetailView.as_view(), name='CSPCApp_student_detail'),
    url(r'^CSPCApp/student/update/(?P<pk>\S+)/$', views.StudentUpdateView.as_view(), name='CSPCApp_student_update'),
)

urlpatterns += (
    # urls for Course
    url(r'^CSPCApp/course/$', views.CourseListView.as_view(), name='CSPCApp_course_list'),
    url(r'^CSPCApp/course/create/$', views.CourseCreateView.as_view(), name='CSPCApp_course_create'),
    url(r'^CSPCApp/course/detail/(?P<pk>\S+)/$', views.CourseDetailView.as_view(), name='CSPCApp_course_detail'),
    url(r'^CSPCApp/course/update/(?P<pk>\S+)/$', views.CourseUpdateView.as_view(), name='CSPCApp_course_update'),
)

urlpatterns += (
    # urls for CourseObject
    url(r'^CSPCApp/courseobject/$', views.CourseObjectListView.as_view(), name='CSPCApp_courseobject_list'),
    url(r'^CSPCApp/courseobject/create/$', views.CourseObjectCreateView.as_view(), name='CSPCApp_courseobject_create'),
    url(r'^CSPCApp/courseobject/detail/(?P<pk>\S+)/$', views.CourseObjectDetailView.as_view(), name='CSPCApp_courseobject_detail'),
    url(r'^CSPCApp/courseobject/update/(?P<pk>\S+)/$', views.CourseObjectUpdateView.as_view(), name='CSPCApp_courseobject_update'),
)

urlpatterns += (
    # urls for UserInfo
    url(r'^CSPCApp/userinfo/$', views.UserInfoListView.as_view(), name='CSPCApp_userinfo_list'),
    url(r'^CSPCApp/userinfo/create/$', views.UserInfoCreateView.as_view(), name='CSPCApp_userinfo_create'),
    url(r'^CSPCApp/userinfo/detail/(?P<pk>\S+)/$', views.UserInfoDetailView.as_view(), name='CSPCApp_userinfo_detail'),
    url(r'^CSPCApp/userinfo/update/(?P<pk>\S+)/$', views.UserInfoUpdateView.as_view(), name='CSPCApp_userinfo_update'),
)

urlpatterns += (
    # urls for Contract
    url(r'^CSPCApp/contract/$', views.ContractListView.as_view(), name='CSPCApp_contract_list'),
    url(r'^CSPCApp/contract/create/$', views.ContractCreateView.as_view(), name='CSPCApp_contract_create'),
    url(r'^CSPCApp/contract/detail/(?P<pk>\S+)/$', views.ContractDetailView.as_view(), name='CSPCApp_contract_detail'),
    url(r'^CSPCApp/contract/update/(?P<pk>\S+)/$', views.ContractUpdateView.as_view(), name='CSPCApp_contract_update'),
)

urlpatterns += (
    # urls for ContractEndInfo
    url(r'^CSPCApp/contractendinfo/$', views.ContractEndInfoListView.as_view(), name='CSPCApp_contractendinfo_list'),
    url(r'^CSPCApp/contractendinfo/create/$', views.ContractEndInfoCreateView.as_view(), name='CSPCApp_contractendinfo_create'),
    url(r'^CSPCApp/contractendinfo/detail/(?P<pk>\S+)/$', views.ContractEndInfoDetailView.as_view(), name='CSPCApp_contractendinfo_detail'),
    url(r'^CSPCApp/contractendinfo/update/(?P<pk>\S+)/$', views.ContractEndInfoUpdateView.as_view(), name='CSPCApp_contractendinfo_update'),
    url(r'^', views.mainPage, name='mainPage'),
)

CSPCApp/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db import fields as extension_fields
from django.utils import timezone


class Student(models.Model):

    # Fields
    school = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    grade = models.SmallIntegerField()
    letter = models.CharField(max_length=2)
    passportserialnumber = models.BigIntegerField()
    passportissued = models.CharField(max_length=128)
    homeaddress = models.CharField(max_length=30)
    phone = models.BigIntegerField()
    parentname = models.CharField(max_length=64)
    parentpassportserialnumber = models.BigIntegerField()
    parentpassportissued = models.CharField(max_length=128)
    parentinn = models.BigIntegerField()
    parenthomeaddress = models.CharField(max_length=128)
    parentphone = models.BigIntegerField()
    created = models.DateTimeField(default=timezone.now)


    class Meta:
        ordering = ('-created',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_student_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_student_update', args=(self.pk,))


class Course(models.Model):

    # Fields
    direction = models.CharField(max_length=32)
    name = models.CharField(max_length=64)
    priceforanhour = models.SmallIntegerField()
    numberofhours = models.SmallIntegerField()
    numberofmounths = models.SmallIntegerField()
    countinaweek = models.SmallIntegerField()


    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_course_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_course_update', args=(self.pk,))


class CourseObject(models.Model):

    # Fields
    timemask = models.BigIntegerField()

    # Relationship Fields
    course = models.ForeignKey('CSPCApp.Course', )
    teacher = models.ForeignKey('CSPCApp.UserInfo', )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_courseobject_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_courseobject_update', args=(self.pk,))


class UserInfo(models.Model):

    # Fields
    name = models.CharField(max_length=64)
    typeofuser = models.SmallIntegerField()

    # Relationship Fields
    user = models.ForeignKey(settings.AUTH_USER_MODEL, )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_userinfo_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_userinfo_update', args=(self.pk,))


class Contract(models.Model):

    # Fields
    number = models.BigIntegerField()
    status = models.SmallIntegerField()

    # Relationship Fields
    student = models.ForeignKey('CSPCApp.Student', )
    courseobject = models.ForeignKey('CSPCApp.CourseObject', )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_contract_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_contract_update', args=(self.pk,))


class ContractEndInfo(models.Model):

    # Fields
    date = models.DateField(default=timezone.now)
    numberofhoursworked = models.SmallIntegerField()

    # Relationship Fields
    contract = models.ForeignKey('CSPCApp.Contract', )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('CSPCApp_contractendinfo_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('CSPCApp_contractendinfo_update', args=(self.pk,))

CSPCApp/forms.py
from django import forms
from .models import Student, Course, CourseObject, UserInfo, Contract, ContractEndInfo


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['school', 'name', 'grade', 'letter', 'passportserialnumber', 'passportissued', 'homeaddress', 'phone', 'parentname', 'parentpassportserialnumber', 'parentpassportissued', 'parentinn', 'parenthomeaddress', 'parentphone', 'created']


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['direction', 'name', 'priceforanhour', 'numberofhours', 'numberofmounths', 'countinaweek']


class CourseObjectForm(forms.ModelForm):
    class Meta:
        model = CourseObject
        fields = ['timemask', 'course', 'teacher']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['name', 'typeofuser', 'user']


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ['number', 'status', 'student', 'courseobject']


class ContractEndInfoForm(forms.ModelForm):
    class Meta:
        model = ContractEndInfo
        fields = ['date', 'numberofhoursworked', 'contract']

CSPCApp/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Student, Course, CourseObject, UserInfo, Contract, ContractEndInfo
from .forms import StudentForm, CourseForm, CourseObjectForm, UserInfoForm, ContractForm, ContractEndInfoForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


class StudentListView(ListView):
    model = Student


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm


class StudentDetailView(DetailView):
    model = Student


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm


class CourseListView(ListView):
    model = Course


class CourseCreateView(CreateView):
    model = Course
    form_class = CourseForm


class CourseDetailView(DetailView):
    model = Course


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseForm


class CourseObjectListView(ListView):
    model = CourseObject


class CourseObjectCreateView(CreateView):
    model = CourseObject
    form_class = CourseObjectForm


class CourseObjectDetailView(DetailView):
    model = CourseObject


class CourseObjectUpdateView(UpdateView):
    model = CourseObject
    form_class = CourseObjectForm


class UserInfoListView(ListView):
    model = UserInfo


class UserInfoCreateView(CreateView):
    model = UserInfo
    form_class = UserInfoForm


class UserInfoDetailView(DetailView):
    model = UserInfo


class UserInfoUpdateView(UpdateView):
    model = UserInfo
    form_class = UserInfoForm


class ContractListView(ListView):
    model = Contract


class ContractCreateView(CreateView):
    model = Contract
    form_class = ContractForm


class ContractDetailView(DetailView):
    model = Contract


class ContractUpdateView(UpdateView):
    model = Contract
    form_class = ContractForm


class ContractEndInfoListView(ListView):
    model = ContractEndInfo


class ContractEndInfoCreateView(CreateView):
    model = ContractEndInfo
    form_class = ContractEndInfoForm


class ContractEndInfoDetailView(DetailView):
    model = ContractEndInfo


class ContractEndInfoUpdateView(UpdateView):
    model = ContractEndInfo
    form_class = ContractEndInfoForm


@login_required
def mainPage(request):
    return render(request, 'CSPCApp/mainPage.html')

CSPCApp/templates/CSPCApp/contract_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_contract_list' %}">Contract Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

CSPCApp/templates/CSPCApp/contract_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_contract_list' %}">Contract Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>number</td>
    <td>status</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.number }}</td>
    <td>{{ object.status }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'CSPCApp_contract_create' %}">Create new Contract</a>
{% endblock %}

CSPCApp/templates/CSPCApp/contractendinfo_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_contractendinfo_list' %}">ContractEndInfo Listing</a></p>
<table class="table">
<tr><td>date</td><td>{{ object.date }}</td></tr>
<tr><td>numberofhoursworked</td><td>{{ object.numberofhoursworked }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit ContractEndInfo</a>

{% endblock %}

CSPCApp/templates/CSPCApp/contractendinfo_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_contractendinfo_list' %}">ContractEndInfo Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

CSPCApp/templates/CSPCApp/course_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_course_list' %}">Course Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

CSPCApp/templates/CSPCApp/course_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_course_list' %}">Course Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>direction</td>
    <td>name</td>
    <td>priceforanhour</td>
    <td>numberofhours</td>
    <td>numberofmounths</td>
    <td>countinaweek</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.direction }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.priceforanhour }}</td>
    <td>{{ object.numberofhours }}</td>
    <td>{{ object.numberofmounths }}</td>
    <td>{{ object.countinaweek }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'CSPCApp_course_create' %}">Create new Course</a>
{% endblock %}

CSPCApp/templates/CSPCApp/courseobject_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_courseobject_list' %}">CourseObject Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

CSPCApp/templates/CSPCApp/courseobject_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_courseobject_list' %}">CourseObject Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>timemask</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.timemask }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'CSPCApp_courseobject_create' %}">Create new CourseObject</a>
{% endblock %}

CSPCApp/templates/CSPCApp/mainPage.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    Главная страница
{% endblock %}

CSPCApp/templates/CSPCApp/student_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_student_list' %}">Student Listing</a></p>
<table class="table">
<tr><td>school</td><td>{{ object.school }}</td></tr>
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>grade</td><td>{{ object.grade }}</td></tr>
<tr><td>letter</td><td>{{ object.letter }}</td></tr>
<tr><td>passportserialnumber</td><td>{{ object.passportserialnumber }}</td></tr>
<tr><td>passportissued</td><td>{{ object.passportissued }}</td></tr>
<tr><td>homeaddress</td><td>{{ object.homeaddress }}</td></tr>
<tr><td>phone</td><td>{{ object.phone }}</td></tr>
<tr><td>parentname</td><td>{{ object.parentname }}</td></tr>
<tr><td>parentpassportserialnumber</td><td>{{ object.parentpassportserialnumber }}</td></tr>
<tr><td>parentpassportissued</td><td>{{ object.parentpassportissued }}</td></tr>
<tr><td>parentinn</td><td>{{ object.parentinn }}</td></tr>
<tr><td>parenthomeaddress</td><td>{{ object.parenthomeaddress }}</td></tr>
<tr><td>parentphone</td><td>{{ object.parentphone }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Student</a>

{% endblock %}

CSPCApp/templates/CSPCApp/student_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{#<p><a class="btn btn-default" href="{% url 'CSPCApp_student_list' %}">Student Listing</a></p>#}
{#<form method="post">#}
	{#{% csrf_token %}#}
	{#{{form|crispy}}#}
	{#<button class="btn btn-primary" type="submit">Submit</button>#}
	{#</form>#}
    <h1>Добавить ученика в базу</h1>
    <br>
<form method="post">
	{% csrf_token %}
    <div>
        <label> Школа </label> <input type="text" name="school" maxlength="64" class="textinput textInput" required id="id_school" />
        <label> Класс </label> <input type="number" name="grade" class="numberinput" required id="id_grade" />
        <label> Литер класса </label> <input type="text" name="letter" maxlength="2" class="textinput textInput" required id="id_letter" />
    </div>
    <br>
    <div class="table2">
        <table align="left" class="table">
            <caption>Ученик</caption>
            <tr>
                <td><label> ФИО </label></td>
                <td><input type="text" name="name" maxlength="64" class="textinput textInput" required id="id_name" /></td>
            </tr>
            <tr>
                <td><label> Серия номер </label></td>
                <td><input type="number" name="passportserialnumber" min="-9223372036854775808" max="9223372036854775807" class="numberinput" required id="id_passportserialnumber" /></td>
            </tr>
            <tr>
                <td><label> Выдан </label></td>
                <td><input type="text" name="passportissued" maxlength="128" class="textinput textInput" required id="id_passportissued" /></td>
            </tr>
            <tr>
                <td><label> Адрес </label></td>
                <td><input type="text" name="homeaddress" maxlength="30" class="textinput textInput" required id="id_homeaddress" /></td>
            </tr>
            <tr>
                <td><label> Телефон </label></td>
                <td><input type="number" name="phone" min="-9223372036854775808" max="9223372036854775807" class="numberinput" required id="id_phone" /></td>
            </tr>
        </table>
    </div>
    <div class="table2">
        <table align="left" class="table">
            <caption>Родитель</caption>
            <tr>
                <td><label> ФИО </label></td>
                <td><input type="text" name="parentname" maxlength="64" class="textinput textInput" required id="id_parentname" /></td>
            </tr>
            <tr>
                <td><label> Серия номер </label></td>
                <td><input type="number" name="parentpassportserialnumber" min="-9223372036854775808" max="9223372036854775807" class="numberinput" required id="id_parentpassportserialnumber" /></td>
            </tr>
            <tr>
                <td><label> Выдан </label></td>
                <td><input type="text" name="parentpassportissued" maxlength="128" class="textinput textInput" required id="id_parentpassportissued" /></td>
            </tr>
            <tr>
                <td><label> ИНН </label></td>
                <td><input type="number" name="parentinn" min="-9223372036854775808" max="9223372036854775807" class="numberinput" required id="id_parentinn" /></td>
            </tr>
            <tr>
                <td><label> Адрес </label></td>
                <td><input type="text" name="parenthomeaddress" maxlength="128" class="textinput textInput" required id="id_parenthomeaddress" /></td>
            </tr>
            <tr>
                <td><label> Телефон </label></td>
                <td><input type="number" name="parentphone" min="-9223372036854775808" max="9223372036854775807" class="numberinput" required id="id_parentphone" /></td>
            </tr>
        </table>
{#        <br>#}
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

{#	<div id="div_id_created" class="control-group">#}
{#		<label for="id_created" class="control-label requiredField">#}
{#		Created<span class="asteriskField">*</span> </label>#}
{#        <div class="controls"> <input type="text" name="created" value="2017-10-28 11:13:48" class="datetimeinput" required id="id_created" /> <input type="hidden" name="initial-created" value="2017-10-28 11:13:48" id="initial-id_created" /> </div>#}
{#	</div>#}
	<button type="submit">Submit</button>
</form>
{% endblock %}

CSPCApp/templates/CSPCApp/student_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_student_list' %}">Student Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>school</td>
    <td>name</td>
    <td>grade</td>
    <td>letter</td>
    <td>passportserialnumber</td>
    <td>passportissued</td>
    <td>homeaddress</td>
    <td>phone</td>
    <td>parentname</td>
    <td>parentpassportserialnumber</td>
    <td>parentpassportissued</td>
    <td>parentinn</td>
    <td>parenthomeaddress</td>
    <td>parentphone</td>
    <td>created</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.school }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.grade }}</td>
    <td>{{ object.letter }}</td>
    <td>{{ object.passportserialnumber }}</td>
    <td>{{ object.passportissued }}</td>
    <td>{{ object.homeaddress }}</td>
    <td>{{ object.phone }}</td>
    <td>{{ object.parentname }}</td>
    <td>{{ object.parentpassportserialnumber }}</td>
    <td>{{ object.parentpassportissued }}</td>
    <td>{{ object.parentinn }}</td>
    <td>{{ object.parenthomeaddress }}</td>
    <td>{{ object.parentphone }}</td>
    <td>{{ object.created }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'CSPCApp_student_create' %}">Create new Student</a>
{% endblock %}

CSPCApp/templates/CSPCApp/userinfo_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_userinfo_list' %}">UserInfo Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>typeofuser</td><td>{{ object.typeofuser }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit UserInfo</a>

{% endblock %}

CSPCApp/templates/CSPCApp/userinfo_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CSPCApp_userinfo_list' %}">UserInfo Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}